### ISSUE TITLE
Bildes profilā

### ISSUE THREAD

**Issue by jklusis** [dnamsons/hiking-app-django#1]
Tās tiek automātiski augšupielādētas iekš "/media/user/<id>/<failanosaukums>", taču saglabājas ar linku "user/<id>/<failanosaukums>". Šī iemesla dēļ visās vietās, kur tiek izmantotas bildes, ir
< img src=" **/media/** {{ u.userprofile.profile_image }}" / >

Tā varētu būt būtiska problēma tad, ja fb vai g+ bildes (pievienojot soctīklu loginu) tiktu uzglabātas kā links šajā pašā profile_image laukā, jo veidotos nepareiza adrese.

**Comment by dnamsons** [comment]
@jklusis Iztiksim

**Comment by jklusis** [comment]
@dnamsons panāc šurp razbainiek
